name: rust_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  flutter_rust_bridge: ^2.7.0

dev_dependencies:
  ffigen: ^16.0.0
  lints: ^4.0.0
  test: ^1.24.0
